name: CI Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # set up java environment
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # build the project using Maven wrapper and install dependencies
      - name: Build with Maven
        run: mvn clean install -U

      # run all tests
      - name: Run all tests
        run:  mvn -pl algo-exercise/getting-started test
