name: CI Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # set up java environment
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      # build the project using Maven wrapper and install dependencies
      - name: Build with Maven
        run: ./mvnw clean install

      # run all tests
      - name: Run all tests
        run: ./mvnw test
